modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="oreslite"
version="1.0.0"
displayName="Ores Lite 1.15.2"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Steve, MCreator"

[[dependencies.oreslite]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




